// AdminTable

export const LOAD_TABLEDATA          = 'LOAD_TABLEDATA';
export const LOAD_TABLEDATA_SUCCESS  = 'LOAD_TABLEDATA_SUCCESS';
export const LOAD_TABLEDATA_FAIL     = 'LOAD_TABLEDATA_FAIL';

export const LOAD_TABLECOLUMNS          = 'LOAD_TABLECOLUMNS';
export const LOAD_TABLECOLUMNS_SUCCESS  = 'LOAD_TABLECOLUMNS_SUCCESS';
export const LOAD_TABLECOLUMNS_FAIL     = 'LOAD_TABLECOLUMNS_FAIL';

export const DELETE_TABLEDATA  = 'DELETE_TABLEDATA';
export const DELETE_TABLEDATA_SUCCESS  = 'DELETE_TABLEDATA_SUCCESS';
export const DELETE_TABLEDATA_FAIL  = 'DELETE_TABLEDATA_FAIL';

export const TABLEDATA_UPDATE  = 'TABLEDATA_UPDATE';
export const TABLEDATA_UPDATE_SUCCESS  = 'TABLEDATA_UPDATE_SUCCESS';
export const TABLEDATA_UPDATE_FAIL  = 'TABLEDATA_UPDATE_FAIL';

export const CHANGE_SELECTED_ROWS = 'CHANGE_SELECTED_ROWS';

// AdminEditDialog

// EDIT
export const SHOW_EDIT_DIALOG = 'SHOW_EDIT_DIALOG';
export const HIDE_EDIT_DIALOG = 'HIDE_EDIT_DIALOG';

// CREATE
export const SHOW_CREATE_DIALOG = 'SHOW_CREATE_DIALOG';
export const HIDE_CREATE_DIALOG = 'HIDE_CREATE_DIALOG';

// AdminEditForm

// EDIT
export const ARCH_INIT_EDIT_FORM_DATA = 'ARCH_INIT_EDIT_FORM_DATA';
export const UPDATE_EDIT_FORM_FIELD_VALUE = 'UPDATE_EDIT_FORM_FIELD_VALUE';

export const SUBMIT_EDIT_FORM = 'SUBMIT_EDIT_FORM';
export const SUBMIT_EDIT_FORM_SUCCESS = 'SUBMIT_EDIT_FORM_SUCCESS';
export const SUBMIT_EDIT_FORM_FAIL = 'SUBMIT_EDIT_FORM_FAIL';

// CREATE
export const INIT_CREATE_FORM_DATA = 'INIT_CREATE_FORM_DATA';
export const UPDATE_CREATE_FORM_FIELD_VALUE = 'UPDATE_CREATE_FORM_FIELD_VALUE';

export const SUBMIT_CREATE_FORM = 'SUBMIT_CREATE_FORM';
export const SUBMIT_CREATE_FORM_SUCCESS = 'SUBMIT_CREATE_FORM_SUCCESS';
export const SUBMIT_CREATE_FORM_FAIL = 'SUBMIT_CREATE_FORM_FAIL';

// AdminAlert

export const SHOW_ADMIN_ALERT = 'SHOW_ADMIN_ALERT';
export const HIDE_ADMIN_ALERT = 'HIDE_ADMIN_ALERT';
